<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBook-Pro-Astaroth.local" failures="1" tests="2" name="qaautomation.august2021.AppTest" time="67.404" errors="0" timestamp="04 Sep 2021 08:55:34 GMT" skipped="0">
  <testcase classname="qaautomation.august2021.AppTest" name="test1" time="32.607"/>
  <testcase classname="qaautomation.august2021.AppTest" name="test" time="34.797">
    <failure message="expected:&lt;fullstackdemofailed&gt; but was:&lt;fullstackdemo&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<fullstackdemofailed> but was:<fullstackdemo>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at qaautomation.august2021.AppTest.test(AppTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- qaautomation.august2021.AppTest -->
